/* Generated By:JavaCC: Do not edit this line. AnalizadorConstants.java */
package Aritmética;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 5;
  /** RegularExpression Id. */
  int DECIMAL_INTEGER_LITERAL = 6;
  /** RegularExpression Id. */
  int DECIMAL_DIGIT = 7;
  /** RegularExpression Id. */
  int ASSIGN = 8;
  /** RegularExpression Id. */
  int MINUS = 9;
  /** RegularExpression Id. */
  int PLUS = 10;
  /** RegularExpression Id. */
  int STAR = 11;
  /** RegularExpression Id. */
  int SLASH = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int OPERATOR_OR_PUNCTUATOR = 14;
  /** RegularExpression Id. */
  int IDENTIFIER = 15;
  /** RegularExpression Id. */
  int ESCAPED_IDENTIFIER = 16;
  /** RegularExpression Id. */
  int IDENTIFIER_NAME = 17;
  /** RegularExpression Id. */
  int IDENTIFIER_START = 18;
  /** RegularExpression Id. */
  int IDENTIFIER_PART = 19;
  /** RegularExpression Id. */
  int UNICODE_LETTER = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_INTEGER_LITERAL>",
    "<DECIMAL_DIGIT>",
    "\"=\"",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\",\"",
    "<OPERATOR_OR_PUNCTUATOR>",
    "<IDENTIFIER>",
    "<ESCAPED_IDENTIFIER>",
    "<IDENTIFIER_NAME>",
    "<IDENTIFIER_START>",
    "<IDENTIFIER_PART>",
    "<UNICODE_LETTER>",
    "\";\"",
    "\"%\"",
  };

}
