/* Generated By:JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package Aritmética;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 6;
  /** RegularExpression Id. */
  int DECIMAL_INTEGER_LITERAL = 7;
  /** RegularExpression Id. */
  int DECIMAL_DIGIT = 8;
  /** RegularExpression Id. */
  int ASSIGN = 9;
  /** RegularExpression Id. */
  int MINUS = 10;
  /** RegularExpression Id. */
  int PLUS = 11;
  /** RegularExpression Id. */
  int STAR = 12;
  /** RegularExpression Id. */
  int SLASH = 13;
  /** RegularExpression Id. */
  int COMMA = 14;
  /** RegularExpression Id. */
  int LPAREN = 15;
  /** RegularExpression Id. */
  int RPAREN = 16;
  /** RegularExpression Id. */
  int IDENTIFIER = 17;
  /** RegularExpression Id. */
  int ESCAPED_IDENTIFIER = 18;
  /** RegularExpression Id. */
  int IDENTIFIER_NAME = 19;
  /** RegularExpression Id. */
  int IDENTIFIER_START = 20;
  /** RegularExpression Id. */
  int IDENTIFIER_PART = 21;
  /** RegularExpression Id. */
  int UNICODE_LETTER = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_INTEGER_LITERAL>",
    "<DECIMAL_DIGIT>",
    "\"=\"",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "<IDENTIFIER>",
    "<ESCAPED_IDENTIFIER>",
    "<IDENTIFIER_NAME>",
    "<IDENTIFIER_START>",
    "<IDENTIFIER_PART>",
    "<UNICODE_LETTER>",
    "\";\"",
    "\"%\"",
  };

}
